set expandtab
set shiftwidth=4
set softtabstop=4
set hlsearch

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

" Use the system clipboard for copy/paste
set clipboard=unnamedplus
